[package]
name = "rocket-accord-example"
version = "0.0.1"
authors = ["Christoffer Buchholz <chris@chrisbuchholz.me>"]

[dependencies]
accord = { path = "../../.." }
rocket = "0.1.4"
rocket_codegen = "0.1.4"
rocket_contrib = "0.1.4"
serde = "0.8.21"
serde_derive = "0.8.21"
serde_json = "0.8.4"
